# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '百度地图' do
pod 'BaiduMapKit', '~> 2.10.2'
pod 'SMS_SDK', '~> 1.2.0'
end

target '百度地图Tests' do

end

target '百度地图UITests' do

end

